-- The coffee shop has consistently maintained its sales in 2023. 
-- The owners are curious to assess their business performance  
-- They want to:
-- Analyze overall coffee sales performance in 2023
-- Identify top-selling coffee products and customer preferences
-- Assess revenue generated by different product categories
-- Evaluate sales trends by month and day
-- Identify any potential areas for improvement or growth opportunities

-- The coffee sales dataset was used for this analysis 
-- The dataset was gotten from Maven Analytics
-- The 'create table statement' used for the creation of permanent tables  for this project is attached below:

CREATE TABLE coffee_sales (
  transaction_id SERIAL PRIMARY KEY,
  transaction_date DATE NOT NULL,
  transaction_qty INT NOT NULL,
  store_id INT NOT NULL,
  store_location VARCHAR(255) NOT NULL,
  product_id INT NOT NULL,
  unit_price DECIMAL(10,2) NOT NULL,
  product_category VARCHAR(255) NOT NULL,
  product_type VARCHAR(255) NOT NULL,
  product_detail VARCHAR(255) NOT NULL
);

-- Afterwards i imported coffee_sales.csv file into PostgreSQL

-- Questions
-- What is the total_quantity?
SELECT SUM(transaction_qty) AS total_quantity
FROM coffee_sales

-- What is the  total_sales?
SELECT SUM(unit_price * transaction_qty) AS total_sales
FROM coffee_sales

-- What is the count of store locations?
SELECT DISTINCT(store_location)
FROM coffee_sales


-- Analyze sales performance by product category?
SELECT product_category, 
       SUM(unit_price * transaction_qty) AS total_sales
FROM coffee_sales
GROUP BY product_category
ORDER BY total_sales;


-- I used this query to remove an outlier called 'Clothing' from product_type column
DELETE FROM coffee_sales
WHERE product_type = 'Clothing';


-- What is the total sales distribution for each product type?
SELECT product_type,
       SUM(unit_price * transaction_qty) AS total_sales
FROM coffee_sales
GROUP BY product_type
ORDER BY total_sales;

-- What is the total sales distribution by store location?
SELECT store_location,
       SUM(unit_price * transaction_qty) AS total_sales
FROM coffee_sales
GROUP BY store_location
ORDER BY total_sales DESC;

-- What is the monthly sales trend?
SELECT
    TO_CHAR(transaction_date, 'Month')AS transaction_month,
    SUM(unit_price * transaction_qty) AS total_sales
FROM coffee_sales
GROUP BY transaction_month
ORDER BY  EXTRACT(MONTH FROM MIN(transaction_date));

-- What is the daily sales trend?
SELECT 
    TO_CHAR(transaction_date, 'Day') AS transaction_day,
    SUM(unit_price * transaction_qty)
FROM coffee_sales
GROUP BY transaction_day
ORDER BY EXTRACT(DAY FROM MIN(transaction_date));

-- INSIGHTS
--   Product Categories:
--   The top-selling product categories are coffee, tea, bakery, and drinking chocolate.
--   The lowest-selling product categories are coffee beans, loose tea, flavors, branded, and ;
--   packaged chocolate.

--   Sales Trends:
--   Sales are lowest in January and February, and highest in June.
--   Sales increase steadily from March to June.

--   Store Locations:
--   Hell's Kitchen has the highest sales, followed by Astoria and Lower Manhattan.
--   The sales margin between the different locations is small.

--   Sales Days:
--   Most sales are made on Monday.
--   Sales are lower on Sundays, Tuesdays, Wednesdays, and Saturdays.
--   Sales increase on Mondays, Thursdays, and Fridays.

--   Top 5 Selling Products:
--   Barista Espresso
--   Brewed Chai tea
--   Hot Chocolate
--   Gourmet brewed coffee
--   Brewed black tea

--   Bottom 5 Selling Products:
--   Black tea
--   Sugar free syrup
--   Organic Chocolate
--   Green tea
--   Green beans  

-- RECOMMENDATIONS
--   Product Categories:
--   The business should focus on promoting and expanding their top-selling product categories: coffee, tea, bakery, and drinking chocolate. These categories generate the most revenue for the business, so it makes sense to prioritize them.
--   It may consider discontinuing or reducing their focus on the lowest-selling product categories: coffee beans, loose tea, flavors, branded, and packaged chocolate. These categories do not generate as much revenue and may not be worth the time and resources to continue selling.

--   Sales Trends:
--   The business should develop strategies to increase sales during the slower months of January and February. These are the two slowest months for the business, so finding ways to boost sales during these times is crucial.
--   It should continue to focus on growth during the peak sales months of March to June. These are the three months when the business makes the most money, so capitalizing on this time is essential.

--   Store Locations:
--   The business should explore opportunities to expand or enhance their Hell's Kitchen location to capitalize on its high sales performance. This location is the top performer, making it an ideal candidate for investment.
--   It should implement strategies to increase sales at their Astoria and Lower Manhattan locations to improve their performance relative to Hell's Kitchen. These two locations do not perform as well as Hell's Kitchen, so finding ways to boost their sales is necessary.

--   Sales Days:
--   The business should leverage marketing and promotional efforts to capitalize on the higher sales days of Monday, Thursday, and Friday. These are the days when customers are most likely to shop, so ensuring they are reached with marketing messages is crucial.
--   It should develop strategies to boost sales on Sundays, Tuesdays, Wednesdays, and Saturdays to reduce the sales gap between these days and the higher-sales days. These are the days when sales are lowest, so finding ways to encourage customers to shop on these days is essential.

--   Top 5 Selling Products:
--   The business should continue to promote and stock their top-selling products: Barista Espresso, Brewed Chai tea, Hot Chocolate, Gourmet brewed coffee, and Brewed black tea. These products are most interesting to customers, so ensuring their availability is essential.
--   It business should consider developing new products or variations of their top-selling products to maintain customer interest and drive sales. This will help keep customers coming back for more.

--   Bottom 5 Selling Products:
--   The business should analyze the reasons why their bottom-selling products are not performing well. There may be various reasons, such as poor placement, lack of marketing, or high prices.
--   It business should consider discontinuing or reducing their focus on these products if there are no clear strategies to improve their sales. Focusing on products that generate revenue is more efficient.

--  Additional Recommendations
--   The business should gather additional customer feedback to gain a deeper understanding of their customers' preferences and needs. This will help develop products and services that customers will love.
--   It  should analyze customer demographics to identify potential target markets for specific products or promotions. This will help reach the right customers with the right message.
--   It should monitor industry trends and competitor activities to stay ahead of the competition. Identifying opportunities to grow the business is crucial.


